/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BankSystem.VIiew;

import BankSystem.Controllers.TransactionController;
import BankSystem.Models.TransactionModels.TransactionModel;
import java.util.UUID;

/**
 *
 * @author adel
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        showHistoryBtn = new javax.swing.JButton();
        transferMoneyBtn = new javax.swing.JButton();
        OpenAccountButton = new javax.swing.JButton();
        ApplyLoanBtn = new javax.swing.JButton();
        withdrawBtn = new javax.swing.JButton();
        BalanceEnquiryBtn = new javax.swing.JButton();
        DepositBtn = new javax.swing.JButton();
        identificationLabel = new javax.swing.JLabel();
        showAllAcountsBtn = new javax.swing.JButton();
        showAllLoansBtn = new javax.swing.JButton();
        showAccountBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Please Select An Option");

        showHistoryBtn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        showHistoryBtn.setText("Show Account History");
        showHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHistoryBtnActionPerformed(evt);
            }
        });

        transferMoneyBtn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        transferMoneyBtn.setText("Transfer Money");
        transferMoneyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferMoneyBtnActionPerformed(evt);
            }
        });

        OpenAccountButton.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        OpenAccountButton.setText("Open New Account");
        OpenAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenAccountButtonActionPerformed(evt);
            }
        });

        ApplyLoanBtn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ApplyLoanBtn.setText("Apply For Loan");
        ApplyLoanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyLoanBtnActionPerformed(evt);
            }
        });

        withdrawBtn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        withdrawBtn.setText("Withdraw Request");
        withdrawBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBtnActionPerformed(evt);
            }
        });

        BalanceEnquiryBtn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        BalanceEnquiryBtn.setText("Balance Enquiry");
        BalanceEnquiryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceEnquiryBtnActionPerformed(evt);
            }
        });

        DepositBtn.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        DepositBtn.setText("DepositRequest");
        DepositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositBtnActionPerformed(evt);
            }
        });

        identificationLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        identificationLabel.setToolTipText("");

        showAllAcountsBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        showAllAcountsBtn.setText("Show All Accounts");
        showAllAcountsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllAcountsBtnActionPerformed(evt);
            }
        });

        showAllLoansBtn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        showAllLoansBtn.setText("Show All Loans");
        showAllLoansBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllLoansBtnActionPerformed(evt);
            }
        });

        showAccountBtn1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        showAccountBtn1.setText("Show Account Details");
        showAccountBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAccountBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DepositBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transferMoneyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OpenAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(showHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addComponent(ApplyLoanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showAllAcountsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BalanceEnquiryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdrawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(304, 304, 304)
                                .addComponent(identificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(showAllLoansBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(538, Short.MAX_VALUE)
                    .addComponent(showAccountBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferMoneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApplyLoanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalanceEnquiryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DepositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllAcountsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(showAllLoansBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(362, Short.MAX_VALUE)
                    .addComponent(showAccountBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(288, 288, 288)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenAccountButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        OpenAccountForm x = new OpenAccountForm();
        x.setVisible(true);
    }//GEN-LAST:event_OpenAccountButtonActionPerformed

    private void withdrawBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        WithdrawForm x = new WithdrawForm();
        x.setVisible(true);

    }//GEN-LAST:event_withdrawBtnActionPerformed

    private void DepositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DepositForm x = new DepositForm();
        x.setVisible(true);
    }//GEN-LAST:event_DepositBtnActionPerformed

    private void transferMoneyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferMoneyBtnActionPerformed
        // TODO add your handling code here:
         this.dispose();
        TransferMoneyForm x = new TransferMoneyForm();
        x.setVisible(true);
    }//GEN-LAST:event_transferMoneyBtnActionPerformed

    private void BalanceEnquiryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceEnquiryBtnActionPerformed
        // TODO add your handling code here:
          this.dispose();
        BalanceEnquiryForm x = new BalanceEnquiryForm();
        x.setVisible(true);
    }//GEN-LAST:event_BalanceEnquiryBtnActionPerformed

    private void ApplyLoanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyLoanBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoanApplyForm x = new LoanApplyForm();
        x.setVisible(true);
    }//GEN-LAST:event_ApplyLoanBtnActionPerformed

    private void showHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHistoryBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        showHistoryForm x = new showHistoryForm();
        x.setVisible(true);
    }//GEN-LAST:event_showHistoryBtnActionPerformed

    private void showAllAcountsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllAcountsBtnActionPerformed
        // TODO add your handling code here:
           this.dispose();
        ShowAllAccountsForm x = new ShowAllAccountsForm();
        x.setVisible(true);
    }//GEN-LAST:event_showAllAcountsBtnActionPerformed

    private void showAllLoansBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllLoansBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ShowAllLoans x = new ShowAllLoans();
        x.setVisible(true);
    }//GEN-LAST:event_showAllLoansBtnActionPerformed

    private void showAccountBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAccountBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showAccountBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyLoanBtn;
    private javax.swing.JButton BalanceEnquiryBtn;
    private javax.swing.JButton DepositBtn;
    private javax.swing.JButton OpenAccountButton;
    public static javax.swing.JLabel identificationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton showAccountBtn1;
    private javax.swing.JButton showAllAcountsBtn;
    private javax.swing.JButton showAllLoansBtn;
    private javax.swing.JButton showHistoryBtn;
    private javax.swing.JButton transferMoneyBtn;
    private javax.swing.JButton withdrawBtn;
    // End of variables declaration//GEN-END:variables
}
